### PR TITLE
remove redundant cast

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by neuecc** [comment]
This is a pattern to avoid boxing when calling interface methods of value types in generics.
It is also used in the DefaultInterpolatedStringHandler.
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/DefaultInterpolatedStringHandler.cs#L263-L273

**Comment by SimonCropp** [comment]
i am confused here. my undestanding is that an "is + assign variable" is more efficient than a "is and a second cast" since it avoids 1 cast. how does boxing come in?

**Comment by neuecc** [comment]
"is + assign variable" to interface causes boxing if T is value type.
however direct cast, JIT detect it and can avoid boxing.

**Comment by SimonCropp** [comment]
fair enough. thanks for the education

**Pull request closed without merging**
